// roupas: {gpt: 'div-gpt-ad-1441392988375-6',sizes: [[768, 1024], [300, 100]], initial: '/95966381/D_Catalogo_Top_Categoria_Roupas', meta: {title: 'ROUPAS', tags: '', description: ''}},
app.factory('Dart', function(){
  return {
    outlet: {
      outlet: {gpt: 'div-gpt-ad-1442869601672-0',sizes: [[768, 1024], [300, 100]], initial: '/95966381/D_Catalogo_Top_Categoria_Outlet', meta: {title: 'OUTLET', tags: '', description: ''}}
    },
    novidades: {
      novidades: {gpt: 'div-gpt-ad-1441392988375-4',sizes: [[768, 1024], [300, 100]], initial: '/95966381/D_Catalogo_Top_Categoria_Novidades', meta: {title: 'Lançamentos', tags: '', description: ''}}
    },
    marca: {
      marca: {gpt: 'div-gpt-ad-1441396716809-0',sizes: [[768, 1024], [300, 100]], initial: '/95966381/D_Catalogo_Top_Categoria_Marcas', meta: {title: 'MARCAS', tags: '', description: ''}}
    },
    'moda-praia':{
      'moda-praia': {gpt: 'div-gpt-ad-1441396492577-0',sizes: [[768, 1024], [300, 100]], initial: '/95966381/D_Catalogo_Top_Categoria_Praia', meta: {title: 'MODA PRAIA', tags: '', description: ''}}
    },
    roupas: {
      roupas: {
        position: [
          {gpt: 'div-gpt-ad-1443463764418-0',sizes: [[784, 35], [784, 170]], initial: '/95966381/D_Catalogo_Top_5_Categoria_Title_Novidades', meta: {title: 'ROUPAS', tags: '', description: ''}},
          {gpt: 'div-gpt-ad-1443210559797-0',sizes: [[255, 162], [250, 250]], initial: '/95966381/D_Catalogo_Top_5.1_Categoria_Novidades', meta: {title: 'ROUPAS', tags: '', description: ''}},
          {gpt: 'div-gpt-ad-1443210559797-1',sizes: [[255, 162], [250, 250]], initial: '/95966381/D_Catalogo_Top_5.2_Categoria_Novidades', meta: {title: 'ROUPAS', tags: '', description: ''}},
          {gpt: 'div-gpt-ad-1443210559797-2',sizes: [[255, 162], [250, 250]], initial: '/95966381/D_Catalogo_Top_5.3_Categoria_Novidades', meta: {title: 'ROUPAS', tags: '', description: ''}},
          {gpt: 'div-gpt-ad-1443210559797-3',sizes: [[255, 162], [250, 250]], initial: '/95966381/D_Catalogo_Top_5.4_Categoria_Novidades', meta: {title: 'ROUPAS', tags: '', description: ''}},
          {gpt: 'div-gpt-ad-1443210559797-4',sizes: [[255, 162], [250, 250]], initial: '/95966381/D_Catalogo_Top_5.5_Categoria_Novidades', meta: {title: 'ROUPAS', tags: '', description: ''}}
        ]
      },
      lingerie: {gpt: 'div-gpt-ad-1441392988375-2',sizes: [[768, 1024], [300, 100]], initial: '/95966381/D_Catalogo_Top_Categoria_Lingerie', meta: {title: 'LINGERIE', tags: '', description: ''}}
    },
    sapatos: {
      sapatos: {gpt: 'div-gpt-ad-1441392988375-7',sizes: [[768, 1024], [300, 100]], initial: '/95966381/D_Catalogo_Top_Categoria_Sapatos', meta: {title: 'SAPATOS', tags: '', description: ''}}
    },
    acessorios: {
      acessorios: {gpt: 'div-gpt-ad-1441392988375-0',sizes: [[768, 1024], [300, 100]], initial: '/95966381/D_Catalogo_Top_Categoria_Acessorios', meta: {title: 'ACESSÓRIOS', tags: '', description: ''}},
      bolsas: {gpt: 'div-gpt-ad-1442838684390-0',sizes: [[768, 1024], [300, 100]], initial: '/95966381/D_Catalogo_Top_Categoria_Bolsas', meta: {title: 'BOLSAS', tags: '', description: ''}}
    },
    marcas: {
      284: {initial: '/95966381/D_Catalogo_Marcas_284', sizes: [[300, 100], [768, 1024]], gpt: 'div-gpt-ad-1441815559158-3', meta: {title: '284', tags: '', description: 'A marca de fast fashion criada pela terceira geração Daslu (Bernardino, Luciana e Marcella Tranchesi e Helena Bordon) oferece informação de moda com ótimo custo-benefício. E agrada em cheio ao público jovem e urbano que busca atitude e versatilidade em tudo que faz e usa. O nome? Trata-se do número do endereço original da Daslu, na Rua Domingos Leme, em São Paulo.'}},
      '2nd-floor': {initial: '/95966381/D_Catalogo_Top_Marcas_2NDFLOOR', sizes: [[300, 100], [768, 1024]], gpt: 'div-gpt-ad-1441815559158-4', meta: {title: '2NDFLOOR', tags: '', description: 'Young, fresh and free. Esse é o espírito da Ellus Second Floor. A marca é expert em transformar ideias frescas em uma moda atual e cheia de bossa e segue o mesmo conceito da Ellus, sua marca-mãe.'}},
      '3am': {initial: '/95966381/D_Catalogo_Top_Marcas_3AM', sizes: [[300, 100], [768, 1024]], gpt: 'div-gpt-ad-1441815559158-5', meta: {title: '3AM', tags: '', description: 'Três sócias, três linhas de produtos. Mas o nome da marca conhecida por suas peças originais, de espírito livre e descontraído é na verdade uma alusão à hora dos sonhos profundos, quando se manifestam os desejos mais secretos. Inspiradas nesses desejos é que são criadas as bijuterias, camisetas e biquínis dessa nova marca que já se firma no mundo fashion.'}},
      '7-for-all-mankind': {initial: '/95966381/D_Catalogo_Top_Marcas_7FORALLMANKIND', sizes: [[300, 100], [768, 1024]], gpt: 'div-gpt-ad-1441815559158-6', meta: {title: '7 FOR ALL MANKIND', tags: '', description: 'Um denim premium com shapes que se adequam ao corpo de qualquer pessoa, de qualquer parte do mundo. Assim são os jeans da 7 For All Mankind, elaborados com design diferenciado e lavagem artesanal. Queridinhos de celebridades internacionais, como Miranda Kerr, Kristen Stewart, Reese Witherspoon, Sofia Vergara e Sarah Jessica Parker, ganharam status de objetos de desejo e trouxeram de volta o jeans aos holofotes da cena fashion.'}},
      abrand: {initial: '/95966381/D_Catalogo_Top_Marcas_A.BRAND', sizes: [[300, 100], [768, 1024]], gpt: 'div-gpt-ad-1441815559158-7', meta: {title: 'ABRAND', tags: '', description: 'Imagine toda sofisticação de estilo e materiais elevada à máxima potência, assim é a A Brand, nova marca do grupo Animale. Com coleções enxutas e superexclusivas, a marca aposta em uma estética feminina e não abre mão dos detalhes para criar peças únicas.'}},
      aniemeyer: {initial: '/95966381/D_Catalogo_Top_Marcas_A.Niemeyer', sizes: [[300, 100], [768, 1024]], gpt: 'div-gpt-ad-1441815559158-8', meta: {title: 'A.NIEMEYER', tags: '', description: 'Fernanda Niemeyer e Renata Alhadeff estão por trás da A.Niemeyer, marca expert no vestir com conforto, mas sem complicação, levando elegância e sofisticação para os momentos mais descompromissados da vida.'}},
      'ac-brazil': {initial: '/95966381/D_Catalogo_Top_Marcas_ACBRAZIL', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-0', meta: {title: 'AC BRAZIL', tags: '', description: 'A marca de bolsas e clutches tem como objetivo destacar uma moda jovem, de qualidade, acessível e sempre atualizada com as últimas tendências do mundo fashion. Para alcançar todos os gostos e estilo, a marca investe em uma ampla variedade de produtos.'}},
      'adidas-originals': {initial: '/95966381/D_Catalogo_Top_Marcas_ADIDASORIGINALS', sizes: [[300, 100], [768, 1024]], gpt: 'div-gpt-ad-1441815559158-9', meta: {title: 'ADIDAS ORIGINALS', tags: '', description: 'Com uma linha de moda casual inspirada pelos primeiros modelos criados por Adi Dassler, a adidas Originals quer celebrar a originalidade. No mix de produtos da marca, que usa o trevo como logotipo, são notáveis referências ao design clássico de modelos da década de 40 e um espírito criativo que dá o tom das coleções da marca.'}},
      'adriana-degreas': {initial: '/95966381/D_Catalogo_Top_Marcas_ADRIANADEGREAS', sizes: [[300, 100], [768, 1024]], gpt: 'div-gpt-ad-1441815559158-10', meta: {title: 'ADRIANA DEGREAS', tags: '', description: 'Formada em Desenho Industrial pela FAAP, a estilista se apaixonou pela moda ainda pequena, na tecelagem e no antiquário dos avós. Criadora de um beachwear poderoso, seu trabalho é repleto de peças com inspiração tropical. Entre suas criações estão maiôs que valorizam as curvas e biquínis com perfume retrô que agradam em cheio as mulheres que não querem abrir mão do glamour, mesmo sob o sol.'}},
      adrianapraca: {initial: '/95966381/D_Catalogo_Top_Marcas_ADRIANAPRAÇA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-11', meta: {title: 'ADRIANA PRAÇA', tags: '', description: 'A estilista Adriana Praça, que fez história com a Madrih, assina sua marca homônima com foco na moda urbana, contemporânea e atemporal.'}},
      'agua-de-coco': {initial: '/95966381/D_Catalogo_Top_Marcas_AGUADECOCO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-12', meta: {title: 'AGUA DE COCO', tags: '', description: 'A Água de Coco, da estilista Liana Thomaz, nasceu nas areias do nordeste brasileiro e ganhou o mundo com seu beachwear autêntico e de qualidade indiscutível.'}},
      alcacuz: {initial: '/95966381/D_Catalogo_Top_Marcas_ALCAÇUZ', sizes: [[300, 100], [768, 1024]], gpt: 'div-gpt-ad-1441815559158-13', meta: {title: 'ALCACUZ', tags: '', description: 'Marca sinônimo de elegância e bem vestir, a veterana Alcaçuz, de Xênia Mozzaquatro e Eniza Bolonha, veste mulheres versáteis e contemporâneas em todos os seus momentos e ocasiões. As coleções são minuciosamente elaboradas, sempre com um olhar apurado e modelagens impecáveis.'}},
      'alexandre-birman': {initial: '/95966381/D_Catalogo_Top_Marcas_ALEXANDREBIRMAN', sizes: [[300, 100], [768, 1024]], gpt: 'div-gpt-ad-1441815559158-14', meta: {title: 'ALEXANDRE BIRMAN', tags: '', description: 'Seguindo uma tradição de família, Alexandre Birman assina sapatos artesanais sofisticados, com desenhos únicos e matérias-primas deluxe, que conquistaram celebridades internacionais e renderam a ele premiações no mercado norte-americano, além de um lugar no CFDA – Conselho de Designers de Moda da América.'}},
      'alexandre-herchcovitch': {initial: '/95966381/D_Catalogo_Top_Marcas_ALEXANDREHERCHCOVITCH', sizes: [[300, 100], [768, 1024]], gpt: 'div-gpt-ad-1441815559158-15', meta: {title: 'ALEXANDRE HERCHCOVITCH', tags: '', description: 'Alexandre Herchcovitch é hoje um dos estilistas brasileiros de maior destaque no mercado nacional e internacional. Sua grife homônima é sinônimo de uma moda sofisticada, com materiais e modelagens inovadoras, com uma proposta individualizada de estilo.'}},
      alixshop: {initial: '/95966381/D_Catalogo_Top_Marcas_ALIXSHOP', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-16', meta: {title: 'ALIX SHOP', tags: '', description: 'A Alix Shop, das empresárias Alessandra Zogbi e Geovana Zhu, acompanha as principais tendências de moda e se inspira na versatilidade da mulher contemporânea para criar peças exclusivas, modernas e confortáveis.'}},
      amapo: {initial: '/95966381/D_Catalogo_Top_Marcas_AMAPÔ', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-17', meta: {title: 'AMAPO', tags: '', description: 'Comandada por Carolina Gold e Pitty Taliani, a Amapô assina os jeans made in Brazil que conquistaram mulheres antenadas. As versões sem lavagem da peça, com cintura alta e boca de sino, são os best sellers da marca.'}},
      anacapri: {initial: '/95966381/D_Catalogo_Top_Marcas_ANACAPRI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-18', meta: {title: 'ANACAPRI', tags: '', description: 'A ANACAPRI acredita que a vida é muita curta para sofrer em cima de um salto alto. Qualidade, personalidade e, principalmente, conforto, são itens que não podem faltar em cada flat que a marca faz. É nesse astral que as coleções são pensadas sob medida para meninas modernas e descoladas..'}},
      'andrea-marques': {initial: '/95966381/D_Catalogo_Top_Marcas_ANDREAMARQUES', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-19', meta: {title: 'ANDREA MARQUES', tags: '', description: 'Depois de anos à frente do time de criação da Maria Bonita, Andrea Marques partiu em voo solo. Apaixonada por estampas, cores e acabamentos delicados, a estilista se inspira em uma silhueta feminina para criar suas peças.'}},
      animale: {initial: '/95966381/D_Catalogo_Top_Marcas_ANIMALE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-20', meta: {title: 'ANIMALE', tags:'', description: 'Por mais de 20 anos, a Animale veste as mulheres brasileiras com um prêt-à-porter premium e sofisticado.'}},
      aragem: {initial: '/95966381/D_Catalogo_Top_Marcas_ARAGEMRIO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-21', meta: {title: 'ARAGEMRIO', tags: '', description: 'A marca carioca Aragem Rio, comandada pelo trio Gabriela Rondinelli, Isabel Jobim e Sophia Fragelli, traduz o lifestyle da Cidade Maravilhosa em coleções despretensiosamente sofisticadas e com o mood do verão.'}},
      'artsy-brasil': {initial: '/95966381/D_Catalogo_Top_Marcas_ARTSYBRASIL', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-22', meta: {title: 'ARTSY BRASIL', tags: '', description: 'A Artsy foge das tendências convencionais com estilo único e atemporal. Com foco na alfaiataria, suas peças possuem modelagem e acabamento diferenciados, tanto na linha urbana quanto no segmento festa. Com coleções voltadas para a mulher elegante e atual, a Artsy combina tecidos de alta qualidade com estampas exclusivas e shapes inusitados.'}},
      ateen: {initial: '/95966381/D_Catalogo_Top_Marcas_ATEEN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-23', meta: {title: 'ATEEN', tags: '', description: 'Com a proposta de construir uma moda urbana sem fronteiras, a Ateen busca inspiração na elegância sensual tipicamente carioca, traduzida em cada coleção com um senso de estilo único. Combinando sofisticação e despojamento sexy, a marca se firmou como referência contemporânea de moda feminina e é preferida de mulheres sofisticadas, cosmopolitas e de espírito jovem em qualquer idade.'}},
      atelierlethicia: {initial: '/95966381/D_Catalogo_Top_Marcas_ATELIERLETHICIA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-24', meta: {title: 'ATELIER LETHICIA', tags: '', description: 'A estilista Lethicia Bronstein é queridinha de famosas e it girls. Expert em vestidos de noiva e de festa, ela leva também para a linha ready to wear suas releituras de clássicos românticos em um estilo moderno. Além disso, têm como marca registrada o trabalho com laços, pérolas, patchwork e rendas importadas.'}},
      aya: {initial: '/95966381/D_Catalogo_Top_Marcas_AYA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-25', meta: {title: 'AYA', tags: '', description: 'Fundada pelas amigas de infância Ana Kurc e Juliana Sverner, a grife é especializada em vestidos de festa, tanto curtos quanto longos. Com foco na modelagem, as criações da dupla são femininas e valorizam a silhueta, remetendo a shapes da década de 1950.'}},
      batiche: {initial: '/95966381/D_Catalogo_Top_Marcas_BATICHE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-26', meta: {title: 'BATICHE', tags: '', description: 'Batas e túnicas perfeitas para a praia são o carro-chefe da Batiche, de Natalie Lubieniecki, marca que utiliza tecidos naturais e fabricação 100% nacional em suas coleções.'}},
      'bee-vee': {initial: '/95966381/D_Catalogo_Top_Marcas_BEEVEE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-27', meta: {title: 'BEEVEE', tags: '', description: 'Materiais brutos como pedras coloridas se transformam em acessórios únicos de inspiração clássica, mas também há espaço para tendências atuais na criação de peças que prometem agradar em cheio as meninas mais antenadas.'}},

      bijouxnet: {initial: '/95966381/D_Catalogo_Top_Marcas_BIJOUXNET', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-28', meta: {title: 'BIJOUX NET', tags: '', description: ''}},

      'blue-man': {initial: '/95966381/D_Catalogo_Top_Marcas_BLUEMAN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-29', meta: {title: 'BLUEMAN', tags: '', description: 'Nascida em Ipanema, a Blue Man de David Azulay criou o biquíni de lacinho em 1972 e, desde então, vem fazendo bonito com sua moda praia original, com estampas exclusivas e uma combinação tipicamente carioca de irreverência e autenticidade.'}},
      bobo: {initial: '/95966381/D_Catalogo_Top_Marcas_BOBÔ', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-30', meta: {title: 'BO.BÔ', tags: '', description: 'A grife do Grupo Restoque cria looks trendy para mulheres jovens e com estilo próprio. A marca é expert em criar produtos de alta qualidade com materiais nobres, como couro, seda, chamois, tricôs, rendas e bordados, marca registrada da Bo. Bô.'}},
      bobstore: {initial: '/95966381/D_Catalogo_Top_Marcas_BOBSTORE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-31', meta: {title: 'BOBSTORE', tags: '', description: 'Há mais de 15 anos no mercado, a Bobstore reflete os desejos reais de seu público cada vez mais fiel. Com estilo inspirado em uma elegância casual, a marca combina desejos de moda atuais à essência da mulher Bobstore.'}},
      brigitte: {initial: '/95966381/D_Catalogo_Top_Marcas_BRIGITTE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-32', meta: {title: 'BRIGITTE', tags: '', description: 'Um beachwear atemporal, com estampas que transitam entre o clássico e moderno. Ideal para mulheres elegantes que buscam detalhes sutis e ao mesmo tempo expressivos, a Brigitte carrega em sua identidade leveza e descontração, para agradar consumidoras que incorporam tal atitude em seu lifestyle.'}},
      'by-nv': {initial: '/95966381/D_Catalogo_Top_Marcas_BYNV', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-33', meta: {title: 'BYNV', tags: '', description: 'Criada por Natalia Vozza, do blog Glam4You, a ByNV surgiu para atender aos desejos das mulheres mais fashionistas. A cada nova coleção, a grife lança novos modelos que se tornam hits imediatos dos closets.'}},

      'caca-filippi': {initial: '/95966381/D_Catalogo_Top_Marcas_CACAFILIPPI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-34', meta: {title: 'CACA FILIPPI', tags: '', description: ''}},
      'calvin-klein': {initial: '/95966381/D_Catalogo_Top_Marcas_CALVINKLEIN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-35', meta: {title: 'CALVIN KLEIN', tags: '', description: 'A conceituada grife americana é expert no denim wear, com calças de modelagem que se adaptam a todos os tipos de corpo e com as lavagens mais cool do momento. Para arrematar, blusas e t-shirts que dão todo um toque descolado ao looks day by day.'}},

      canal: {initial: '/95966381/D_Catalogo_Top_Marcas_CANAL', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-36', meta: {title: 'CANAL', tags: '', description: 'A grife contemporânea traduz as principais tendências internacionais em peças cheias de charme para o dia a dia. A cada coleção, a marca traz básicos espertos e estampas que vão colorir o seu guarda-roupas.'}},
      'candy-brown': {initial: '/95966381/D_Catalogo_Top_Marcas_CANDYBROWN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-37', meta: {title: 'CANDYBROWN', tags: '', description: 'De perfume retrô e cores vibrantes, a moda festa da grife está entre as mais queridinhas das it girls. Ideal para mulheres que amam a delicadeza da renda, a sensualidade de recortes estratégicos e um caimento perfeito.'}},
      'carla-dsantis': {initial: '/95966381/D_Catalogo_Top_Marcas_CARLADSANTIS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-38', meta: {title: 'CARLA D SANTIS', tags: '', description: 'Unanimidade entre as experts em moda, como as blogueiras Lala Rudge e Thássia Naves, os acessórios da Carla D Santis são resultado do olhar afinado da dupla Carla e Camila D Santis, mãe e filha, que criam peças originais com materiais de primeira. No mix de produtos da marca o diferencial são as pedras brasileiras, clássicas e eternamente chiques.'}},
      cavendish: {initial: '/95966381/D_Catalogo_Top_Marcas_CAVENDISH', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-39', meta: {title: '', tags: 'CAVENDISH', description: 'A mulher Cavendish gosta de moda e tem prazer em se vestir bem. Moderna, mas sofisticada, aprecia peças cuidadosamente trabalhadas com bordados, rendas, tules e pedrarias. '}},
      'cecilia-machado': {initial: '/95966381/D_Catalogo_Top_Marcas_CECILIAMACHADO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-40', meta: {title: 'CECILIA MACHADO', tags: '', description: 'O trabalho artesanal da marca resulta em acessórios de pegada rústica e charmosa. As bolsas trançadas Cecilia Machado são a cara da tropicalidade brasileira e vão da praia à cidade.'}},

      'cecilia-prado': {initial: '/95966381/D_Catalogo_Top_Marcas_CECILIAPRADO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-41', meta: {title: 'CECILIA PRADO', tags: '', description: ''}},

      'chiringuitas-ibiza': {initial: '/95966381/D_Catalogo_Top_Marcas_CHIRINGUITASIBIZA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-42', meta: {title: 'CHIRINGUITAS IBIZA', tags: '', description: 'As sandálias de desenvolvimento e fabricação no Brasil são uma releitura da tradicional Avarca espanhola. O nome da marca faz referência aos Chiringuitos, que são os famosos bares pé na areia das regiões litorâneas da Espanha, que convidam a todos a relaxar e aproveitar o momento.'}},
      'cia-maritima': {initial: '/95966381/D_Catalogo_Top_Marcas_CIAMARITIMA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-43', meta: {title: 'CIA MARITIMA', tags: '', description: 'Marca referência no beachwear nacional, a Cia Marítima cria um conceito de moda praia que vai muito além dos biquínis. Com 20 anos de mercado, explora novos tecidos e modelagens exclusivas a cada coleção, traduzindo as melhores tendências mundiais em um estilo que procura valorizar ainda mais a beleza das mulheres.'}},
      'cica-e-renata': {initial: '/95966381/D_Catalogo_Top_Marcas_CIÇAERENATA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-44', meta: {title: 'CICA E RENATA', tags: '', description: 'Mãe e filha, Ciça e Renata assinam bijoux com bossa, inspiradas nas necessidades de mulheres contemporâneas que precisam de complementos versáteis para qualquer ocasião.'}},
      cielle: {initial: '/95966381/D_Catalogo_Top_Marcas_CIELLE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-45', meta: {title: 'CIELLE', tags: '', description: 'Francesa de nascimento e brasileira de coração, Céline assina peças delicadas e atuais em prata para sua marca Cielle. Com uma proposta cool, as joias da marca transmitem mensagens e emoções, e se transformam em modelo de expressão de quem as usa.'}},
      'claudia-arbex': {initial: '/95966381/D_Catalogo_Top_Marcas_CLAUDIAARBEX', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-1', meta: {title: 'CLAUDIA ARBEX', tags: '', description: 'Claudia Arbex criar acessórios para mulheres que reconhecem a importância de um complemento ímpar na composição do look. Com uma visão vanguardista, a designer usa a malha de metal como marca-registrada na construção de suas peças e foi a primeira a ilustrar um catálogo de tendências internacional da Swarovski Elements.'}},
      'claudia-marisguia': {initial: '/95966381/D_Catalogo_Top_Marcas_CLAUDIAMARISGUIA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-46', meta: {title: 'CLAUDIA MARISGUIA', tags: '', description: 'Do encontro profissional das irmãs Nívia e Claudia Marisguia nasceu, em 1989, a grife de bijoux Claudia Marisguia. Desde então a marca vem criando peças que combinam emoção, design e qualidade sempre com um resultado atual e apelo contemporâneo.'}},

      cle: {initial: '/95966381/D_Catalogo_Top_Marcas_CLÉ', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-47', meta: {title: 'CLE', tags: '', description: ''}},

      'clube-bossa': {initial: '/95966381/D_Catalogo_Top_Marcas_CLUBEBOSSA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-48', meta: {title: 'CLUBE BOSSA', tags: '', description: 'Kaftãs estampados, biquínis de caimento perfeito e maiôs com recortes modernos são a especialidade dessa marca de moda praia de luxo.'}},

      ccm: {initial: '/95966381/D_Catalogo_Top_Marcas_CMM', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-49', meta: {title: 'CMM', tags: '', description: 'Looks fitness com informação de moda para você aderir a um lifestyle saudável com muito estilo. As coleções CCM trazem tecidos tecnológicos com easy care, estampas exclusivas e modelagem cheia de engenharia, que valoriza o corpo.'}},

      converse: {initial: '/95966381/D_Catalogo_Top_Marcas_CONVERSE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-50', meta: {title: 'CONVERSE', tags: '', description: 'Desde 1908 a Converse vem construindo sua história com uma rica herança de calçados legendários como, por exemplo, o Chuck Taylor All Star. Clássica entre as marcas de tênis, a Converse se reinventa a cada temporada e com a sua linha "Premium" não seria diferente. Materiais inusitados e estampas atuais animam os modelos da marca, combinando estilo e conforto sem perder o seu DNA.'}},
      cori: {initial: '/95966381/D_Catalogo_Top_Marcas_CORI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-51', meta: {title: 'CORI', tags: '', description: 'Marca reconhecida no cenário da moda nacional, a CORI assina coleções conectadas aos desejos femininos de seu tempo, vestindo mulheres contemporâneas com sofisticação e simplicidade.'}},
      corporeum: {initial: '/95966381/D_Catalogo_Top_Marcas_CORPOREUM', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-52', meta: {title: 'CORPOREUM', tags: '', description: 'A Corporeum prima por coleções elaboradas onde o clássico e o atemporal se aliam ao espírito inovador e contemporâneo, pontuando o verdadeiro DNA carioca – uma sofisticação despojada.'}},
      costume: {initial: '/95966381/D_Catalogo_Top_Marcas_COSTUME', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-53', meta: {title: 'COSTUME', tags: '', description: 'Jovem e cheia de bossa, a Costume conquistou há décadas o seu espaço com coleções fresh, um jeanswear que veste superbem e um olhar antenado, para saber sempre o que as meninas querem vestir.'}},
      coven: {initial: '/95966381/D_Catalogo_Top_Marcas_COVEN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-54', meta: {title: 'COVEN', tags: '', description: 'A Coven, marca mineira que tem no tricô seu carro-chefe, surgiu a partir da verdadeira vocação da estilista Liliane Rebehy para a moda. Com formação em arquitetura, ela trocou as linhas retas por uma expressividade diferente para criar peças contemporâneas com um lado artesanal.'}},
      'cris-barros': {initial: '/95966381/D_Catalogo_Top_Marcas_CRISBARROS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-55', meta: {title: 'CRIS BARROS', tags: '', description: 'Depois de trocar a carreira de modelo pela criação, a estilista paulistana Cris Barros tornou-se referência com sua marca homônima. As formas simples com detalhes únicos, combinadas à construção em moulage com tecidos nobres e excelente caimento, são a chave de peças com acabamento perfeito que conquistaram uma clientela fiel.'}},
      cruise: {initial: '/95966381/D_Catalogo_Top_Marcas_CRUISE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-56', meta: {title: 'CRUISE', tags: '', description: 'Fundadora da marca de acessórios Pollignanno Al Mare, Fernanda Piva Vidigal se juntou a Adriana Pelosini Moreira, ex-Daslu e Alexandre Birman, para criar a Cruise, marca de roupas e acessórios superexclusivos. Criada em 2013, a marca explora a ideia de look completo,  com bijoux, sapatos e roupas, com destaque para as peças em couro com cortes impecáveis.'}},

      dalaibeachwear: {initial: '/95966381/D_Catalogo_Top_Marcas_DALAIBEACHWEAR', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-57', meta: {title: 'DELAI BEACH WEAR', tags: '', description: ''}},

      danibaratella: {initial: '/95966381/D_Catalogo_Top_Marcas_DANIBARATELLA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-58', meta: {title: 'DANI BARATELLA', tags: '', description: 'As peças de perfume boho seguem o esquema fast fashion, sempre ligadas às tendências mais quentinhas da estação. Os acessórios da marca são uma boa maneira de elevar o status fashion do look com aquela cara de chic sem esforço.'}},
      'daniele-mabe': {initial: '/95966381/D_Catalogo_Top_Marcas_DANIELEMABE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-59', meta: {title: 'DANIELE MABE', tags: '', description: 'As coleções da Daniele Mabe têm estilo único. A estilista começou sua carreira explorando as possibilidades da malha, em diferentes formas, volumes e recortes. Hoje, o material ganhou companheiros sofisticados: seda, algodão e linho são as matérias-primas para peças versáteis e atemporais.'}},
      daslu: {initial: '/95966381/D_Catalogo_Top_Marcas_DASLU', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-60', meta: {title: 'DASLU', tags: '', description: 'Cafezinho, bom papo e compras entre amigas foram os ingredientes para o sucesso que viria a se chamar Daslu. Comandada por Eliana Tranchesi, a loja pioneira logo virou referência no mercado de luxo do país e passou a desenvolver peças para sua marca homônima que, com coleções de estilos e materiais nobres, traduz exatamente o que a mulher brasileira espera da moda.'}},
      desabandone: {initial: '/95966381/D_Catalogo_Top_Marcas_DESABANDONE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-61', meta: {title: 'DESA BANDONE', tags: '', description: 'O projeto Desabandone, da blogueira Bruna Pacífico, promove a conscientização sobre a situação dos animais abandonados. A campanha possui peças exclusivas, com parte dos recursos revertidos para ONGs amigas e para projetos da Desabandone.'}},
      'dolores-iguacel': {initial: '/95966381/D_Catalogo_Top_Marcas_DOLORESIGUACEL', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-62', meta: {title: 'DOLORES IGUACEL', tags: '', description: 'As peças de Dolores Iguacel são únicas. Com inspirações atuais e um estilo fresh, a designer argentina combina materiais inusitados para criar acessórios originais, feitos à mão, para sua marca homônima.'}},
      dressto: {initial: '/95966381/D_Catalogo_Top_Marcas_DRESSTO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-63', meta: {title: 'DRESS TO', tags: '', description: 'Para recriar o espírito do lifestyle carioca, a marca aposta em pitades de ousadia e muito humor. O conceito fica claro nas peças delicadas e despretenciosas e nas estampas superfemininas.'}},
      duza: {initial: '/95966381/D_Catalogo_Top_Marcas_DUZA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-64', meta: {title: 'DUZA', tags: '', description: 'Cocktail rings, brincos poderosos e colares de tirar o fôlego fazem da marca de Fernanda Bertoni um must-have entre as garotas descoladas. Com referências de peso como Coco Chanel e Yves Saint Laurent, a moça viaja sempre para Paris e NY em busca das melhores tendências e apura o olhar a cada coleção.'}},
      eclectic: {initial: '/95966381/D_Catalogo_Top_Marcas_ECLECTIC', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-65', meta: {title: 'ECLECTIC', tags: '', description: 'Nascida em Ipanema, a Eclectic combina a personalidade carioca despretensiosa e leve com informações clássicas de moda, o resultado são coleções femininas e sempre originais.'}},
      egrey: {initial: '/95966381/D_Catalogo_Top_Marcas_EGREY', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-66', meta: {title: 'EGREY', tags: '', description: 'Seguindo a tradição familiar, Eduardo Mahfuz Toldi abraça seu DNA fashion para criar peças em tricô com referências urbanas. Já ganhou espaço nos melhores closets.'}},
      ellus: {initial: '/95966381/D_Catalogo_Top_Marcas_ELLUS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-67', meta: {title: 'ELLUS', tags: '', description: 'Criada em 1972 por Nelson Alvarenga, a Ellus é sinônimo de jeanswear ousado e autêntico. A marca se renova a cada temporada com frescor e originalidade característicos em cada uma de suas coleções.'}},
      'ellus-acessorios': {initial: '/95966381/D_Catalogo_Top_Marcas_ELLUSACESSÓRIOS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-68', meta: {title: 'ELLUS ACESSÓRIOS', tags: '', description: 'Com o mesmo espírito ousado e autêntico de sua coleção jeanswear, a Ellus assina acessórios deluxe e carregados de atitude.'}},

      'emporio-anna': {initial: '/95966381/D_Catalogo_Top_Marcas_EMPÓRIOANNA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-69', meta: {title: 'EMPORIO ANNA', tags: '', description: ''}},
      apiphanie: {initial: '/95966381/D_Catalogo_Top_Marcas_APIPHANIE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-70', meta: {title: 'APIPHANIE', tags: '', description: ''}},

      'espaco-fashion': {initial: '/95966381/D_Catalogo_Top_Marcas_ESPAÇOFASHION', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-71', meta: {title: 'ESPAÇO FASHION', tags: '', description: 'As irmãs Bianca e Camila Bastos comandam a Espaço Fashion, grife carioca que conquistou os guarda-roupas de mulheres antenadas com suas coleções jovens de pegada urbana, equilibradas com a feminilidade e um viés casual chic que fazem parte do espírito da marca.'}},
      eva: {initial: '/95966381/D_Catalogo_Top_Marcas_EVA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-72', meta: {title: 'EVA', tags: '', description: 'A Eva é uma marca para uma mulher que sabe o que quer e não tem medo de ousar e se diverte na hora de se vestir. Lançada em janeiro de 2012, a label feminina do grupo Reserva veste uma mulher cosmopolita que não acha a menor graça em ser básica.'}},

      fabula: {initial: '/95966381/D_Catalogo_Top_Marcas_FÁBULA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-73', meta: {title: 'FABULA', tags: '', description: ''}},

      farm: {initial: '/95966381/D_Catalogo_Top_Marcas_FARM', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-74', meta: {title: 'FARM', tags: '', description: 'Foi com estampas, cores e muita personalidade que a FARM surgiu na zona sul do Rio e conquistou o Brasil. À frente da marca estão Marcello Bastos e Kátia Barros, dupla expert em interpretar como ninguém o estilo das meninas do Rio, criando uma moda balneário descontraída, que traz um pouquinho do estilo de vida carioca para a selva urbana de São Paulo.'}},
      fethie: {initial: '/95966381/D_Catalogo_Top_Marcas_FETHIE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-75', meta: {title: 'FETHIE', tags: '', description: 'A Fethie foi criada para mulheres que não se conformam com o básico.  Querem ir além... com peças que, apesar de casuais, são chiques e atuais. As coleções são permeadas por detalhes e segredinhos feitos à mão, sempre com uma pitada de charme.'}},
      fillity: {initial: '/95966381/D_Catalogo_Top_Marcas_FILLITY', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-76', meta: {title: 'FILLITY', tags: '', description: 'A Fillity acredita em mulheres seguras com estilo baseado na reinterpretação dos clássicos, que se reinventam a cada temporada, sem perder seu estilo e nunca abrir mão da feminilidade.'}},
      fit: {initial: '/95966381/D_Catalogo_Top_Marcas_FIT', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-77', meta: {title: 'FIT', tags: '', description: 'A Fit cria uma moda simples e chic, sempre com coleções que privilegiam formas limpas valorizadas por tecidos de alta qualidade. A cada coleção, a marca convida artistas plásticos que desenvolvem estampas originais e exclusivas, e se mantém fiel ao desejo de produzir peças únicas, confortáveis e atemporais.'}},
      'flower-power': {initial: '/95966381/D_Catalogo_Top_Marcas_FLOWERPOWER', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-78', meta: {title: 'FLOWER POWER', tags: '', description: 'Há 14 anos no mercado, a Flower Power já desenvolveu peças para marcas como NK, Daslu, ABrand e Le Lis Blanc. Como private label, elabora um trabalho diferenciado em modelos de malharia e bordados manuais que são sua marca registrada.'}},
      'fm-pantalons': {initial: '/95966381/D_Catalogo_Top_Marcas_FMPANTALONS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-79', meta: {title: 'FM PANTALONS', tags: '', description: 'Os bottoms são o carro-chefe da FM Pantalons, das amigas Manoela Whitaker e Flavia Cury. Peças superexclusivas, estampas e modelagens que valorizam o corpo feminino colocaram a marca no topo da wishlist de fashionistas e mulheres que fogem do óbvio na hora de se vestir.'}},
      'for-the-win': {initial: '/95966381/D_Catalogo_Top_Marcas_FORTHEWIN', sizes: [768, 1024], gpt: 'div-gpt-ad-1443193869828-1', meta: {title: 'FOR THE WIN', tags: '', description: 'A For The Win nasceu para acompanhar a mulher que tem um ritmo acelerado dentro e fora da academia. Com este ponto de partida, a marca une estilo, conforto e tecnologia em suas criações.'}},
      'forum-lingerie': {initial: '/95966381/D_Catalogo_Top_Marcas_FORUMLINGERIE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-80', meta: {title: 'FORUM LINGERIE', tags: '', description: 'A Forum Lingerie empresta um olhar de moda às suas coleções, sempre abusando de cores e prints superfemininos.'}},
      fyi: {initial: '/95966381/D_Catalogo_Top_Marcas_FYI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-81', meta: {title: 'FYI', tags: '', description: 'Livre e com vontade de experimentar, assim foi criada a FYI, marca do grupo Animale, que nasceu da busca constante por informação. Com um mix de ideias e estilos que torna cada coleção única, a grife tem direção criativa de Renata Simões e quer estimular em suas clientes o desejo de singularidade por meio da experimentação.'}},
      'gabriela-pires': {initial: '/95966381/D_Catalogo_Top_Marcas_GABRIELAPIRES', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-82', meta: {title: 'GABRIELA PIRES', tags: '', description: 'Gabriela Pires transforma metais, cristais e pedras naturais em bijoux únicas com uma pitada de sofisticação, adaptando as tendências da vez ao gosto da mulher brasileira.'}},

      'gala-basic-wear': {initial: '/95966381/D_Catalogo_Top_Marcas_GALABASICWEAR', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-83', meta: {title: 'GALA BASIC WEAR', tags: '', description: 'Focada em produzir básicos de qualidade, a marca tem linhas fixas de t-shirts que aliam bom caimento e tecidos especiais. Seus modelos versáteis e cores neutras são ótimos aliados para criar looks no melhor estilo casual chic.'}},

      garnus: {initial: '/95966381/D_Catalogo_Top_Marcas_GARNÚS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-84', meta: {title: 'GARNÚS', tags: '', description: 'Depois de desenhar para marcas como Zoomp, Le Lis Blanc e a internacional Byblos, Graciana Arnús criou sua marca própria, a GArnús que veste mulheres de atitude casual chic, antenada e cosmopolita.'}},
      ghetz: {initial: '/95966381/D_Catalogo_Top_Marcas_GHETZ', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-85', meta: {title: 'GHETZ', tags: '', description: 'Alta tecnologia e trabalho manual impecável são a fórmula da Ghetz para transformar o tricô em peças sofisticadas com contornos High-Tech Couture. A marca tem direção criativa do Dinamarquês Kim Laursen, ex-braço direto do estilista francês Christian Lacroix, e se destaca por seu estilo único e sensual.'}},
      gig: {initial: '/95966381/D_Catalogo_Top_Marcas_GIG', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-86', meta: {title: 'GIG', tags: '', description: 'A GIG pode ser considerada a Missoni brasileira. Expert em tricôs, a marca mineira é responsável pelo desenvolvimento de peças para grifes internacionais e sabe explorar os fios de forma cool e chic. A marca traz um verão com tramas elaboradas, franjas e um toque de brilho glam, que atualizam o handmade e agradam as it-girls.'}},
      'gio-bernardes': {initial: '/95966381/D_Catalogo_Top_Marcas_GIOBERNARDES', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-87', meta: {title: 'GIO BERNARDES', tags: '', description: 'Há 20 anos no mercado, Gio Bernardes é conhecida por suas criações que abusam da mistura de materiais como pedras, cristais, pérolas, couros e cordões. O resultado são acessórios sofisticados na medida, perfeitos para as adeptas de uma elegância casual.'}},
      'gisele-bundchen-intimates': {initial: '/95966381/D_Catalogo_Top_Marcas_GISELEBUNDCHEN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-88', meta: {title: 'GISELE BUNDCHEN INTIMATES', tags: '', description: 'A über top Gisele Bündchen, como diretora criativa da marca, participa ativamente de todo o processo de desenvolvimento da linha de lingerie que leva seu nome. Com a proposta de oferecer peças sexy e sofisticada ao mesmo tempo, a grife usa tecidos como sedas, cetins e microfibras levíssimas.'}},
      'giuliana-romanno': {initial: '/95966381/D_Catalogo_Top_Marcas_GIULIANAROMANNO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-89', meta: {title: 'GIULIANA ROMANNO', tags: '', description: 'Conhecida por suas peças de alfaiataria com corte impecável, a designer Giuliana Romanno tem no cuidado especial com acabamentos, tecidos e modelagens outra marca registrada de suas coleções, sempre sofisticadas e atemporais, para mulheres modernas e cosmopolitas.'}},

      gluck: {initial: '/95966381/D_Catalogo_Top_Marcas_GLUCK', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-90', meta: {title: 'GLUCK', tags: '', description: ''}},

      guilhermina: {initial: '/95966381/D_Catalogo_Top_Marcas_GUILHERMINA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-91', meta: {title: 'GUILHERMINA', tags: '', description: 'Com um cuidado quase artesanal, as peças da Guilhermina são cuidadosamente elaboradas com materiais premium e seguem as principais tendências da moda mundial. Apesar de jovem, a marca ultrapassou as fronteiras do Brasil e vem se tornando referência de sapatos deluxe.'}},
      'hector-abertazzi': {initial: '/95966381/D_Catalogo_Top_Marcas_HECTORALBERTAZZI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-92', meta: {title: 'HECTOR ALBERTAZZI', tags: '', description: 'Durante anos Hector Albertazzi desenvolveu as linhas de bijoux das marcas mais hypadas do Brasil. Hoje, a grife que leva seu nome produz acessórios de peso com design exclusivo, através de um minucioso trabalho artesanal. As pedras usadas são lapidadas em oficinas próprias e tudo é cuidadosamente banhado a ouro ou prata.'}},
      'hype-it': {initial: '/95966381/D_Catalogo_Top_Marcas_HYPEIT', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-93', meta: {title: 'HYPE IT', tags: '', description: 'A Hype it nasceu do desejo de combinar conforto e estilo em básicos atualizados com modelagens supermodernas.'}},
      idarro: {initial: '/95966381/D_Catalogo_Top_Marcas_IDARRÔ', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-94', meta: {title: 'IDARRÔ', tags: '', description: 'As flats da Idarrô sempre têm um detalhe que deixa cada peça mais interessante. Com preços convidativos e estilo de sobra, as sapatilhas e rasteiras da marca foram pensadas para mulheres que gostam de chamar a atenção para os pés.'}},

      illesteva: {initial: '/95966381/D_Catalogo_Top_Marcas_ILLESTEVA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-95', meta: {title: 'ILLESTEVA', tags: '', description: 'Os óculos Illesteva são feitos a mão na França e Itália, em parceria com os principais fabricantes de óculos de luxo do mundo, e usando materiais como acetato e titânio no design de cada uma de suas armações. Entre as fãs famosas da marca, Rihanna, Sienna Miller e Alexa Chung.'}},

      iorane: {initial: '/95966381/D_Catalogo_Top_Marcas_IORANE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-96', meta: {title: 'IORANE', tags: '', description: 'Com olhar apurado, a Iorane, marca mineira de Belo Horizonte, foca suas coleções nas tendências mais atuais do cenário fashion com um mix de produtos que inclui peças para o dia e para a noite. Iorane Rabello, estilista à frente da marca, desenvolve seus modelos para uma mulher moderna e antenada que ama acessórios e estampas exclusivas.'}},
      'isabella-giobbi': {initial: '/95966381/D_Catalogo_Top_Marcas_IS//BELLAPORISABELLAGIOBBI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-97', meta: {title: 'IS\BELLA POR ISABELLA GIOBBI', tags: '', description: 'Uma das principais etiquetas de moda high end do país, Isabella Giobbi veste mulheres como a própria estilista: chiques, cosmopolitas e low profile. Tecidos nobres, acabamento impecável e coleções que conversam entre si ajudaram a marca a fazer história.   '}},
      isla: {initial: '/95966381/D_Catalogo_Top_Marcas_ISLA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-98', meta: {title: 'ISLA', tags: '', description: 'Sinônimo de luxo atemporal, as bolsas da Isla são elaboradas com peles exóticas, cristais, pedrarias e madrepérolas, em um resultado singular. Comparadas a joias, as peças da marca são perfeitas para arrematar produções sofisticadas.'}},
      isolda: {initial: '/95966381/D_Catalogo_Top_Marcas_ISOLDA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-99', meta: {title: 'ISOLDA', tags: '', description: 'Com estampas originais carregadas de tropicalismo e cores pop, a Isolda segue o conceito da roupa como uma obra de arte. A grife é expert na criação de peças que despertam desejo imediato e chamam atenção em cliques de streetstyle.'}},
      'j-chermann': {initial: '/95966381/D_Catalogo_Top_Marcas_JCHERMANN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-100', meta: {title: 'J. CHERMANN', tags: '', description: 'A marca dessa paulistana cheia de bossa tem nas t-shirts o seu ponto forte. O segredo: estampas irreverentes  e detalhes preciosos, que dão vontade de usar 24/7.'}},
      'jo-de-mer': {initial: '/95966381/D_Catalogo_Top_Marcas_JODEMER', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-101', meta: {title: 'JO DE MER', tags: '', description: 'A JO DE MER foi criada pela ex-editora de moda Amalia Spinardi, que trabalhou vários anos no mercado editorial, em revistas como a Capricho e a Elle. Os biquínis e maiôs cheios de bossa são inspirados no “savoire vivre” de mulheres chiques, que gostam da vida ao mar. Pense em Jackie O e seu filhos na Ilha de Skorpios, Brigitte Bardot em Búzios nos anos 60, Jade Jagger de férias em Ibiza ou Gisele pegando um bronzeado no Rio de Janeiro.'}},
      jodri: {initial: '/95966381/D_Catalogo_Top_Marcas_JODRI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-102', meta: {title: 'JODRI', tags: '', description: 'Depois de ter trabalhado criando para grifes como Yves Saint Laurent e Emanuel Ungaro em Paris, Adriana Caruso passou a assinar suas coleções próprias na Jodri, marca brasileira que nasceu do desejo de produzir vestidos atemporais, com caimento perfeito e acabamento impecável.'}},
      joge: {initial: '/95966381/D_Catalogo_Top_Marcas_JOGÊ', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-103', meta: {title: 'JOGÊ', tags: '', description: 'Uma das primeiras marcas nacionais de moda íntima e para dormir, a Jogê acredita na mulher naturalmente sexy e linda. Ela tem um sorriso, uma atitude, um olhar cativante e é nesse clima que as peças de cada coleção trazem todo o DNA da marca.'}},
      'john-john': {initial: '/95966381/D_Catalogo_Top_Marcas_JOHNJOHN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-104', meta: {title: 'JOHN JOHN', tags: '', description: 'Os jeans da John John são verdadeiros objetos de desejo e preferidos pelas celebridades em todo o mundo. Resultado da combinação de um trabalho constante de pesquisa em novas técnicas de lavagem, costura e modelagem, tem um caimento único e estão sempre antenados. Além do jeans, a marca expandiu seu mix de produtos para uma linha de alfaiataria desconstruída, sapatos, lingeries e acessórios.'}},
      'juliana-manzini': {initial: '/95966381/D_Catalogo_Top_Marcas_JULIANAMANZINI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-105', meta: {title: 'JULIANA MANZINI', tags: '', description: 'A paixão de Juliana Manzini pela moda ganha vida nas peças de sua marca homônima de acessórios. Com uma clientela fiel de peso, que inclui nomes como Fernanda Paes Leme, Giovana Antonelli, Paola Oliveira, Danielle Winits e Sabrina Sato, a marca faz parte de um seleto grupo com direito de uso da marca CRYSTALLIZED™ - Swarovski Elements.'}},
      'karen-walker': {initial: '/95966381/D_Catalogo_Top_Marcas_KARENWALKER', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-106', meta: {title: 'KAREN WALKER', tags: '', description: 'Os óculos da grife neozelandesa misturam uma atitude fashion e excêntrica ao mesmo tempo. Vendida em mais de 30 países pelo mundo, as criações da designer homônima reúnem fãs como Alexa Chung, Charlize Theron e Anne Hathaway.'}},
      'kate-spade-new-york': {initial: '/95966381/D_Catalogo_Top_Marcas_KATESPADENEWYORK', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-107', meta: {title: 'KATE SPADE NEW YORK', tags: '', description: 'A grife americana Kate Spade é conhecida por seu DNA fun e irreverente. Os relógios da marca seguem exatamente essa linha, com um design jovem e atual. Escolha seu queridinho e arremate seus looks com muita personalidade.'}},
      keds: {initial: '/95966381/D_Catalogo_Top_Marcas_KEDS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-108', meta: {title: 'KEDS', tags: '', description: 'Desde 1916 a Keds se reinventa a cada temporada com seus sneakers de sola de borracha, um clássico fashion absoluto.   '}},
      ket: {initial: '/95966381/D_Catalogo_Top_Marcas_KET', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-109', meta: {title: 'K&T', tags: '', description: 'A marca carioca tem a preocupação de desenvolver peças ultrafemininas, mas que ao mesmo tempo têm uma alma despretensiosa. As coleções têm uma sofisticação cool, com tricôs, calças de cortes impecáveis e acessórios que dão um toque charmoso aos looks.'}},
      'kika-simonsen': {initial: '/95966381/D_Catalogo_Top_Marcas_KIKASIMONSEN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-110', meta: {title: 'KIKA SIMONSEN', tags: '', description: 'Peças de corte impecável e alfaiataria atemporal ganham graça e charme com as estampas exclusivas criadas pela artista plástica Kika Simonsen e pintadas à mão. A cartela de cores ganha vida no mix de tecidos nobres e cheios de movimento.'}},
      lale: {initial: '/95966381/D_Catalogo_Top_Marcas_LALE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-111', meta: {title: 'LALE', tags: '', description: 'A marca carioca, sob o comando da diretora criativa Luiza Botto, aposta em peças fashionistas para mulheres que não têm medo de seguir tendências. Um dos principais focos da grife são as modelagens-assinatura, como quimonos descolados e bodies recortados, além da tropicalização das trends saídas diretamente das passarelas.'}},
      'la-rouge-belle': {initial: '/95966381/D_Catalogo_Top_Marcas_LAROUGEBELLE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-112', meta: {title: 'LA ROUGE BELLE', tags: '', description: 'Criada pela blogueira Lalá Rudge, a La Rouge Belle é reflexo natural da sua paixão por moda e inovação. A marca de underwear é feminina, atemporal, chique, confortável e sexy na medida. São 6 linhas, que vão do basiquinho à alta-costura, com rendas francesas e seda pura.'}},
      lauf: {initial: '/95966381/D_Catalogo_Top_Marcas_LAUF', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-113', meta: {title: 'LAUF', tags: '', description: 'O trio Anna Guinle, Ana Oliva e Marina Rovery comanda a Lauf, marca especializada em roupas esportivas com apelo fashion, para mulheres exigentes que estão sempre em busca de melhores resultados, mas sem abrir mão do estilo.'}},
      leeloo: {initial: '/95966381/D_Catalogo_Top_Marcas_LEELOO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-114', meta: {title: 'LEELOO', tags: '', description: 'A carioca Leeloo começou a sua história em 1999 e, desde então, vem fazendo uma moda com muito estilo e sofisticação, sem esquecer do charme e da bossa do Rio de Janeiro.'}},
      lehkin: {initial: '/95966381/D_Catalogo_Top_Marcas_LEHKIN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-115', meta: {title: 'LEHKIN', tags: '', description: 'Estampas próprias e excelência em modelagem são a especialidade da Lehkin, marca de moda praia da dupla Fernanda Magalhães e Giuliana Calvo.'}},
      'le-lis-blanc': {initial: '/95966381/D_Catalogo_Top_Marcas_LELISBLANC', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-116', meta: {title: 'LE LIS BLANC', tags: '', description: 'A Le Lis Blanc é referência em estilo e faz uma moda para mulheres elegantes, cosmopolitas e com essência nacional. Graças a um trabalho de pesquisa mundo afora, a marca adapta as melhores tendências do circuito fashion ao biotipo e à personalidade de suas clientes, em coleções cheias de personalidade.'}},
      'le-lis-blanc-casa': {initial: '/95966381/D_Catalogo_Top_Marcas_LELISBLANCCASA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-117', meta: {title: 'LE LIS BLANC CASA', tags: '', description: 'A Le Lis Blanc Casa oferece uma linha de decoração e artigos para casa com uma seleção apurada de peças exclusivas. Garimpados no exterior em pequenas quantidades, os produtos da marca são perfeitos para renovar a casa com estilo.   '}},
      'lenny-niemeyer': {initial: '/95966381/D_Catalogo_Top_Marcas_LENNYNIEMEYER', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-118', meta: {title: 'LENNY NIEMEYER', tags: '', description: 'A Lenny, comandada pela estilista Lenny Niemeyer, surgiu da vontade de uma moda praia sofisticada e com charme carioca. Paisagista renomada na capital paulista, Lenny levou o gosto pela natureza para as estampas de suas criações que, além de biquínis e maiôs, inclui bolsas, sapatos, acessórios e uma coleção de roupas e malhas. Com 20 anos de história, a marca é sinônimo de sofisticação em matéria de moda praia no Brasil e no mundo.'}},
      'le-specs': {initial: '/95966381/D_Catalogo_Top_Marcas_LESPECS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-119', meta: {title: 'LE SPECS', tags: '', description: 'Marca australiana ícone dos anos 1980, a Le Specs voltou ao mercado em 2006 e, desde então, seus óculos de sol inconfundíveis ganharam status de acessório indispensável de fashionistas e celebridades como Beyoncé, Cara Delevingne, Olivia Palermo e Miranda Kerr.'}},
      letage: {initial: '/95966381/D_Catalogo_Top_Marcas_LETAGE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-120', meta: {title: 'LETAGE', tags: '', description: 'A Letage adapta as principais tendências da temporada ao estilo sofisticado e exigente de mulheres que sabem o que querem.'}},
      'leticia-peranovich': {initial: '/95966381/D_Catalogo_Top_Marcas_LETICIAPERANOVICH', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-121', meta: {title: 'LETÍCIA PERANOVICH', tags: '', description: 'As semijóias de Letícia Peranovich, há dez anos no mercado, arrematam looks das mulheres mais sofisticadas. A peças de extrema qualidade são feitas de ouro ou prata, e adornadas com rubis, safiras, esmeraldas, entre outras pedras preciosas.'}},
      'leticia-sarabia': {initial: '/95966381/D_Catalogo_Top_Marcas_LETICIASARABIA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-122', meta: {title: 'LETÍCIA SARABIA', tags: '', description: 'Em sua marca homônima Letícia Sarabia assina peças produzidas em número limitado que combinam design exclusivo, sofisticação, durabilidade e conforto.'}},
      'levi-s': {initial: '/95966381/D_Catalogo_Top_Marcas_LEVIS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-123', meta: {title: 'LEVI\'S', tags: '', description: 'Desde 1873, a Levi´s® simboliza o estilo americano clássico e effortless cool com sua tradição em produzir jeans, peça de roupa mais reconhecida, e imitada, no mundo todo.'}},

      'lila-deux': {initial: '/95966381/D_Catalogo_Top_Marcas_LILADEUX', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-124', meta: {title: 'LILA DEUX', tags: '', description: 'Destinada a um público jovem, a marca tem como principal preocupação o acabamento refinado de suas peças, aliado a uma alfaiataria de caimento impecável. A grife adapta as tendências mundiais mais bombadas a seu design clean e moderno.'}},
      'lili-sampedro': {initial: '/95966381/D_Catalogo_Top_Marcas_LILISAMPEDRO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-125', meta: {title: 'LILI SAMPEDRO', tags: '', description: 'A marca Lilisampedro foi criada em 2011 com a vontade de inovar o beachwear brasileiro. As fundadoras não queriam apenas uma roupa bonita para ir a praia, mas sim algo que fosse confortável, elegante, fazendo com que a mulher se sinta valorizada e feminina.'}},

      lille: {initial: '/95966381/D_Catalogo_Top_Marcas_LILLE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-126', meta: {title: 'LILLE', tags: '', description: 'A linha de bijoux nasceu do desejo da designer Natalia Chaim de criar uma marca com identidade jovem e feminina. O design exclusivo é alinhado ao rigor em qualidade, e resulta em brincos-desejo com pedras multicoloridas, capazes de dar um up em qualquer produção.'}},
      'lilly-sarti': {initial: '/95966381/D_Catalogo_Top_Marcas_LILLYSARTI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-127', meta: {title: 'LILLY SARTI', tags: '', description: 'Dupla por trás da Lilly Sarti, as irmãs Lilly e Renata Sarti conquistaram uma clientela fiel com peças atemporais e cheias de identidade, que têm a alta qualidade e a flexibilidade de shapes como marca registrada.'}},
      livo: {initial: '/95966381/D_Catalogo_Top_Marcas_LIVO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-128', meta: {title: 'LIVO', tags: '', description: 'Criada em 2012, a Livo cria óculos que se destacam pela excelência em qualidade e design diferenciado. Todas as peças são feitas com acetato importado da Itália e produzidas à mão no Brasil. As lentes solares contam com proteção contra raios UVA/UVB, proporcionando segurança e o máximo conforto em qualquer situação.'}},
      'loft-747': {initial: '/95966381/D_Catalogo_Top_Marcas_LOFT747', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-129', meta: {title: 'LOFT 747', tags: '', description: 'A Loft 747 propõe uma moda para a mulher real, que usa tendências a seu favor para estar sempre pronta e, acima de tudo, linda em qualquer lugar.'}},

      lollita: {initial: '/95966381/D_Catalogo_Top_Marcas_', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-130', meta: {title: 'LOLLITA', tags: '', description: ''}},

      lool: {initial: '/95966381/D_Catalogo_Top_Marcas_LOOL', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-131', meta: {title: 'LOOL', tags: '', description: 'Conhecida por seus acessórios de peso, a LOOL surgiu sob o olhar irreverente de sua idealizadora Luiza Setubal que, atenta aos movimentos do mercado da moda, sentia falta de uma multimarcas de acessórios. Com uma curadoria especial, o mix de produtos da LOOL mistura o estilo pessoal de Luiza à identidade única de sua marca.'}},
      'luiza-barcelos': {initial: '/95966381/D_Catalogo_Top_Marcas_LUIZABARCELOS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-132', meta: {title: 'LUIZA BARCELOS', tags: '', description: 'Na Luiza Barcelos a atenção aos detalhes vem de fábrica e cada peça da marca é tratada como um produto artesanal, mesmo com toda a tecnologia usada em seu desenvolvimento. Com tanto cuidado, os sapatos da marca mineira conquistaram não só as mulheres brasileiras, mas também consumidoras dos quatro cantos do mundo.'}},

      magrella: {initial: '/95966381/D_Catalogo_Top_Marcas_MAGRELLA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-133', meta: {title: 'MAGRELLA', tags: '', description: 'A luxuosa multimarcas brasiliense desenvolveu uma coleção própria, recheada de peças para serem usadas no dia a dia e que podem se estender a ocasiões mais especiais - tudo com qualidade extrema, seguindo os padrões já exigidos há anos pelas clientes da loja.'}},

      'marc-by-marc-jacobs-watches': {initial: '/95966381/D_Catalogo_Top_Marcas_MARCBYMARCJACOBSWATCHES', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-134', meta: {title: 'MARC BY MARC JACOBS WATCHES', tags: '', description: 'Os relógios da Marc by Marc Jacobs, marca acessível do incensado estilista americano, carregam o mesmo espírito de vanguarda da Marc Jacobs, mas com um viés jovem e irreverente que também dá o tom dos relógios da marca.'}},
      margot: {initial: '/95966381/D_Catalogo_Top_Marcas_MARGOT', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-135', meta: {title: 'MARGOT', tags: '', description: 'A Margot é especialista em interpretar tendências de moda atuais em sapatos e bolsas que carregam a essência da marca.'}},
      'maria-dolores': {initial: '/95966381/D_Catalogo_Top_Marcas_MARIADOLORES', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-136', meta: {title: 'MARIA DOLORES', tags: '', description: 'Conhecida por sua sofisticação e ousadia, as coleções da grife abusam de materiais nobres, design autoral e estilo irreverente. Entre os principais materiais usados, destacam-se a ônix e a ágata verde. Ideal para mulheres de estilo moderno que gostam de acessórios de pegada geométrica.'}},
      'maria-filo': {initial: '/95966381/D_Catalogo_Top_Marcas_MARIAFILÓ', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-137', meta: {title: 'MARIA FILÓ', tags: '', description: 'A Maria Filó se inspira nas mulheres que se expressam através da sua feminilidade. Em cada criação, a atenção ao novo e o carinho pelos detalhes. Nascida no coração de Ipanema em 1997, a marca combina o moderno e o clássico para valorizar as formas femininas e deixar as mulheres ainda mais especiais.'}},
      'mariah-rovery': {initial: '/95966381/D_Catalogo_Top_Marcas_MARIAHROVERY', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-138', meta: {title: 'MARIAH ROVERY', tags: '', description: 'Mariah Rovery desenvolve acessórios exclusivos e com muita personalidade em sua marca homônima. Na linha FLEX JEWEL, a designer assina pulseiras, brincos e colares de borracha com cores vibrantes e pegada fun.'}},
      'maries-robe-de-nuit': {initial: '/95966381/D_Catalogo_Top_Marcas_MARIESROBEDENUIT', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-139', meta: {title: 'MARIES ROBE DE NUIT', tags: '', description: 'Criada por verdadeiras filhas da arte, a Maries Robe de Nuit já nasce com um passado nobre.  A marca das irmãs Cristiana e Paula Trussardi herdou a tradição do sleepwear deluxe da empresa de seu pai. Utilizando materiais nobres como a seda e a renda francesa, elas criam um universo de sonhos que, vai do dia a dia ao enxoval de noiva.'}},
      'market-33': {initial: '/95966381/D_Catalogo_Top_Marcas_MARKET33', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-140', meta: {title: 'MARKET 33', tags: '', description: 'A Market 33 vem chamando atenção pelo garimpo de produtos up to date com o que há de mais bacana na moda. Com um mix fresh que agrada em cheio quem ama uma moda jovem e cheia de estilo, a marca traduz as tendências mais atuais do circuito fashion em novidades constantes, sob medida para um público antenado que procura informação de moda a preços superconvidativos.'}},
      'market-33-casa': {initial: '/95966381/D_Catalogo_Top_Marcas_MARKET33CASA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-141', meta: {title: 'MARKET 33 CASA', tags: '', description: 'A Market 33 Casa é composta por uma seleção de produtos para casa que flertam com tendências superatuais, tudo com o mesmo conceito e bom gosto de sua marca-mãe. Aromas irresistíveis da linha de velas, home sprays e difusores deixam qualquer ambiente mais aconchegante. Na linha de papelaria, a marca oferece blocos e cadernos de anotação com padronagens únicas e, na seleção de gifts, mimos para presentear e enfeitar a casa.'}},
      'market-33-off': {initial: '/95966381/D_Catalogo_Top_Marcas_MARKET33OFF', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-142', meta: {title: 'MARKET 33 OFF', tags: '', description: 'Marca exclusiva do OQVestir, a Market 33 garimpou e reuniu achados de coleções de outras temporadas com ótimos descontos em sua segunda linha, a Market 33 OFF.'}},
      melissa: {initial: '/95966381/D_Catalogo_Top_Marcas_MELISSA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-143', meta: {title: 'MELISSA', tags: '', description: 'O plástico é a matéria-prima dos pares da Melissa, marca brasileira que vai além da moda, combinando cultura, arte e tecnologia para transformar sonhos de plástico em sapatos supercriativos, que já renderam parcerias com grandes nomes do circuito fashion como Karl Lagerfeld e Vivienne Westwood.'}},
      'melon-melon': {initial: '/95966381/D_Catalogo_Top_Marcas_MELONMELON', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-144', meta: {title: 'MELON MELON', tags: '', description: 'Marca de t-shirts pensada especialmente para mulheres modernas e com estilo inusitado, a Melon Melon explora o universo contemporâneo em suas criações sempre divertidas e com um apelo de moda.'}},
      memo: {initial: '/95966381/D_Catalogo_Top_Marcas_MEMO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-145', meta: {title: 'MEMO', tags: '', description: 'A Memo, marca de activewear e loungewear, desenvolve peças com tecidos de alta tecnologia para quem procura conforto e beleza para aproveitar os momentos em que cuidar de si mesma é o mais importante.'}},
      'michael-kors-watches': {initial: '/95966381/D_Catalogo_Top_Marcas_MICHAELKORSWATCHES', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-146', meta: {title: 'MICHAEL KORS WATCHES', tags: '', description: 'A Memo, marca de activewear e loungewear, desenvolve peças com tecidos de alta tecnologia para quem procura conforto e beleza para aproveitar os momentos em que cuidar de si mesma é o mais importante.'}},
      missinclof: {initial: '/95966381/D_Catalogo_Top_Marcas_MISSINCLOF', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-147', meta: {title: 'MISSINCLOF', tags: '', description: 'Tathiana Ventri e Silvia Freitas criam roupas que não encontram para comprar, mas que gostariam de vestir. Num mix de modernidade e bom-gosto, a Missinclof mostra que não é apenas mais uma grife fashion. É a receita para vestir uma mulher contemporânea, exigente, e que sabe muito bem o que quer. Atenção para a linha de camisaria!'}},
      mixed: {initial: '/95966381/D_Catalogo_Top_Marcas_MIXED', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-148', meta: {title: 'MIXED', tags: '', description: 'A Mixed, fundada por Riccy Souza Aranha em 1988, veste mulheres contemporâneas, sofisticadas e antenadas, em todo os seus momentos.'}},
      'miz-couture': {initial: '/95966381/D_Catalogo_Top_Marcas_MIZCOUTURE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-149', meta: {title: 'MIZ.;COUTURE', tags: '', description: 'Lingerie jovem para quem procura conforto com uma pitada de bossa, assim são as coleções da miz.;couture, nova aposta de underwear do OQVestir.'}},
      mob: {initial: '/95966381/D_Catalogo_Top_Marcas_MOB', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-150', meta: {title: 'MOB', tags: '', description: 'Com quase três décadas de bagagem na cena fashion brasileira, a MOB faz uma moda versátil, jovem e, sobretudo, usável.'}},
      mumi: {initial: '/95966381/D_Catalogo_Top_Marcas_MUMI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-151', meta: {title: 'MUMI', tags: '', description: 'A Mumi, de Martina Galeotti, se inspira na moda balneário para assinar peças desenvolvidas em baixa escala, e com estampas exclusivas, que levam a felicidade de uma tarde de verão para o guarda-roupa de qualquer temporada.'}},
      'my-shoes': {initial: '/95966381/D_Catalogo_Top_Marcas_MYSHOES', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-152', meta: {title: 'MY SHOES', tags: '', description: 'Saiba Mais  Há pouco tempo no mercado, a My Shoes, de Alexandre Zolko, nasceu do desejo de unir referências de moda superatuais em coleções que prometem agradar em cheio as mulheres exigentes e com muita personalidade.'}},
      nannacay: {initial: '/95966381/D_Catalogo_Top_Marcas_NANNACAY', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-153', meta: {title: 'NANNACAY', tags: '', description: 'Misto de marca e projeto de moda, a Nannacay® tem a missão de ajudar pessoas a desenvolver potenciais criativos, incentivando a produção artesanal de acessórios únicos que refletem a cultura dos povos que trabalham em parceria com marca.'}},
      'natalia-chaim': {initial: '/95966381/D_Catalogo_Top_Marcas_NATALIACHAIM', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-154', meta: {title: 'NATALIA CHAIM', tags: '', description: 'Natalia Chaim nasceu há dois anos e vem ganhando cada vez mais admiradores. As coleções da marca são compostas por peças contemporâneas entre o casual e o fashion, mesclando formas modernas e ao mesmo tempo clássicas. Referência no mercado de luxo de semi joias, as peças prezam pela leveza e pelo acabamento impecável, sempre pensando no universo feminino.'}},
      'nica-kessler': {initial: '/95966381/D_Catalogo_Top_Marcas_NICAKESSLER', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-155', meta: {title: 'NICA KESSLER', tags: '', description: 'Nica é jovem, mas traz no currículo cursos na Saint Martins School, em Londres, e um máster em moda na Escuela Superior de Diseño de Moda Felicidad Duce, em Barcelona. Essa bagagem foi passaporte para o sucesso. Aos 28 anos, ela é uma estilista madura que domina o métier. Sua roupa tem qualidade, valoriza o único, o original e o pessoal para dar vida a uma moda essencialmente feminina, carregada de sofisticação e personalidade.'}},
      olympiah: {initial: '/95966381/D_Catalogo_Top_Marcas_OLYMPIAH', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-156', meta: {title: 'OLYMPIAH', tags: '', description: 'A Olympiah assina coleções jovens, atuais e cosmopolitas para mulheres que apreciam o mix de modernidade e sofisticação sem abrir mão do conforto.'}},

      'oqvestir-casa': {initial: '/95966381/D_Catalogo_Top_Marcas_OQVESTIRCASA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-157', meta: {title: 'OQVESTIRCASA', tags: '', description: ''}},

      'pat-pat-s': {initial: '/95966381/D_Catalogo_Top_Marcas_PATPATS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-158', meta: {title: 'PAT PAT\'S', tags: '', description: 'Ao lado de sua filha Andréa, a estilista carioca Patrícia Viera, sinônimo de couro de primeira, criou a Pat Pat´s. As viagens pelo mundo e o olhar apurado de Andréa se unem aos anos de sucesso de Patrícia para a criação de peças incríveis e antenadas para a fresh brand.'}},
      'patricia-geyer': {initial: '/95966381/D_Catalogo_Top_Marcas_PATRÍCIAGEYER', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-159', meta: {title: 'PATRÍCIA GEYER', tags: '', description: 'Desde 2010, Patricia Geyer assina coleções sofisticadas para mulheres femininas e de atitude em sua etiqueta homônima. O DNA clássico, aliado a tecidos nobres como seda e viscose, é a essência da marca, que atualiza shapes atemporais com detalhes como recortes e fendas.'}},
      'paula-hermanny': {initial: '/95966381/D_Catalogo_Top_Marcas_PAULAHERMANNY', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-160', meta: {title: 'PAULA HERMANNY', tags: '', description: 'Em sua marca homônima, Paula Hermanny assina um ready-to-wear feminino, simples e versátil para todos os momentos. Com inspirações atemporais e shapes que valorizam a silhueta, a marca oferece peças em número limitado, para garantir que cada criação seja única e especial.'}},
      'paula-raia': {initial: '/95966381/D_Catalogo_Top_Marcas_PAULARAIA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-161', meta: {title: 'PAULA RAIA', tags: '', description: 'Depois do sucesso da Raia de Goeye, Paula Raia alça voo solo no comando da grife que leva seu nome. Arquiteta de formação, ela não perdeu a conexão estética com sua primeira profissão, particularidade que se reflete em cada uma de suas coleções. Combinando materiais nobres como a seda, ela dá vida a peças leves, sempre elaboradas com um cuidado quase artesanal.'}},
      'paula-torres': {initial: '/95966381/D_Catalogo_Top_Marcas_PAULATORRES', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-162', meta: {title: 'PAULA TORRES', tags: '', description: 'A designer Paula Torres investe em uma proposta contemporânea para criar seus produtos. Com sapatos exclusivos e feitos à mão, a grife investe em coleções atemporais e democráticas, sempre com peças-desejo que podem ser usadas em diferentes momentos da mesma mulher.'}},
      perky: {initial: '/95966381/D_Catalogo_Top_Marcas_PERKY', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-163', meta: {title: 'PERKY', tags: '', description: 'Foi com um mix de cores e estampas que a brasileira Perky reinventou o conceito de alpargata, para quem acredita que a vida pode ser mais leve.'}},
      'pop-up-store': {initial: '/95966381/D_Catalogo_Top_Marcas_POPUPSTORE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-164', meta: {title: 'POP UP STORE', tags: '', description: 'A Pop Up Store tem como conceito principal o Fast Fashion, oferecendo novidades constantes. Sempre antenada, a marca dita estilo e comportamento, acompanhando todas as tendências do mundo afora, com preços acessíveis ao seu público.'}},
      pratamania: {initial: '/95966381/D_Catalogo_Top_Marcas_PRATAMANIA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-165', meta: {title: 'PRATAMANIA', tags: '', description: 'A marca fundada em 1986 vem passando de geração em geração, criando semi-joias delicadas, a preços superconvidativos. Sempre antenada, a Pratamania traz peças atuais e exclusivas, perfeitas para arrematar todos os seus looks.'}},
      prayah: {initial: '/95966381/D_Catalogo_Top_Marcas_PRAYAH', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-166', meta: {title: 'PRAYAH', tags: '', description: 'A Prayah nasceu do desejo de uma marca inovadora de beachwear nacional, com criações que se adequam às necessidades da mulher atual, que busca conforto, qualidade e design exclusivo.'}},
      princess: {initial: '/95966381/D_Catalogo_Top_Marcas_PRINCESS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-167', meta: {title: 'PRINCESS', tags: '', description: 'A Princess, de Karen Abuhab, nasceu da vontade de propor uma nova forma de se vestir. Apostando na originalidade, mas sem esquecer das principais tendências de cada temporada, a marca desenvolve peças e estampas exclusivas para mulheres estilosas e com uma pitada romântica.'}},
      'pri-schiavianato': {initial: '/95966381/D_Catalogo_Top_Marcas_PRISCHIAVINATO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-168', meta: {title: 'PRI SCHIAVINATO', tags: '', description: 'No mercado de acessórios desde 1998, Pri Schiavinato atende a um público seleto que busca peças exclusivas, com materiais diversos e inspirações atuais.'}},
      pynablu: {initial: '/95966381/D_Catalogo_Top_Marcas_PYNABLU', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-169', meta: {title: 'PYNABLU', tags: '', description: 'A Pynablu nasceu de uma paixão pelo diferente e inovador. Antonela Frugiuele, criadora e estilista da marca, assina um cool wear para mulheres que buscam frescor e novidade com inspirações que fogem do que a tendência dita e seguem seu próprio caminho.'}},
      'raphael-faci': {initial: '/95966381/D_Catalogo_Top_Marcas_RAPHAELFACI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-170', meta: {title: 'RAPHAEL FACI', tags: '', description: ''}},

      rapsodia: {initial: '/95966381/D_Catalogo_Top_Marcas_RAPSODIA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-171', meta: {title: 'RAPSODIA', tags: '', description: 'Marca de moda com estilo boêmio e roqueiro, a Rapsodia nasceu em Buenos Aires, na Argentina com uma identidade livre, aventureira e ultra feminina.'}},
      'reinaldo-lourenco': {initial: '/95966381/D_Catalogo_Top_Marcas_REINALDOLOURENÇO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-172', meta: {title: 'REINALDO LOURENÇO', tags: '', description: 'Com criações modernas, mas sempre usando referências clássicas, as coleções de Reinaldo Lourenço são elaboradas com tecidos nobres e cartelas de cores neutras. Buscando inspiração no cotidiano, o estilista cria para mulheres contemporâneas que gostam de moda, design e têm prazer em se vestir.'}},
      'renata-campos': {initial: '/95966381/D_Catalogo_Top_Marcas_RENATACAMPOS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-173', meta: {title: 'RENATA CAMPOS', tags: '', description: 'Marca mineira com mais de 17 anos de história, Renata Campos é expert em criar peças com tricô e couro em modelagens que vestem superbem, sempre adaptando tendências atuais ao gosto de suas clientes.'}},
      'renata-vicintin': {initial: '/95966381/D_Catalogo_Top_Marcas_RENATAVICINTIN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-174', meta: {title: 'RENATA VICINTIN', tags: '', description: 'Depois de trabalhar na criação, produção e desenvolvimento de acessórios para marcas como Osklen, Fit, Rose Benedetti, Schutz, Opera Rock e Doc Dog, a designer de acessórios e moda praia, Renata Vicintin, passou a criar peças para sua marca homônima, sempre com um toque pessoal e diferenciado.'}},

      repetto: {initial: '/95966381/D_Catalogo_Top_Marcas_REPETTO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-175', meta: {title: 'REPETTO', tags: '', description: 'A pedido de Brigitte Bardot, em 1956, Rose Repetto adaptou suas famosas sapatilhas para bailarinas a um sapato para ser usado no dia a dia. Nasceu um sucesso imediato! Desde então, a marca segue sua premissa de sapatilhas leves e cheias de graça, mas com muito luxo, e voltadas a um público exigente.'}},

      richards: {initial: '/95966381/D_Catalogo_Top_Marcas_RICHARDS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-176', meta: {title: 'RICHARDS', tags: '', description: 'Com o lema "sabor de férias no cotidiano", a Richards faz moda associada a um estilo de vida original, informal e requintado, para mulheres que procuram qualidade sem esquecer do conforto.'}},
      'rodrigo-potechi': {initial: '/95966381/D_Catalogo_Top_Marcas_RODRIGOPOTECHI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-177', meta: {title: 'RODRIGO POTECHI', tags: '', description: 'Metais, pedras naturais, zircônias e cristais trabalhados em um minucioso processo de lapidação sintetizam o conceito de fashion jewerly de Rodrigo Potechi. O designer assina semi joias sofisticadas e atemporais com o luxo, requinte e exclusividade que estão no DNA de sua marca homônima.'}},
      'rosa-cha': {initial: '/95966381/D_Catalogo_Top_Marcas_ROSACHÁ', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-178', meta: {title: 'ROSA CHÁ', tags: '', description: 'Fundada nos anos 1990, a Rosa Chá está de volta com uma proposta que vai muito além do beachwear. As novidades são as roupas, e os acessórios, assinados pela marca,  que pretende ser símbolo de atitude e comportamento para uma nova geração.'}},
      'rosana-bernardes': {initial: '/95966381/D_Catalogo_Top_Marcas_ROSANABERNARDES', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-179', meta: {title: 'ROSANA BERNARDES', tags: '', description: 'Em 1991, a designer inaugurou sua primeira loja em Ipanema. Em 2000, já exportava suas peças para a Venezuela, Suíça, Portugal e Espanha. Maxicolares de inspiração Art Déco são o must-have dessa temporada.'}},
      sacada: {initial: '/95966381/D_Catalogo_Top_Marcas_SACADA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-180', meta: {title: 'SACADA', tags: '', description: 'Marca carioca consolidada no mercado de moda, a Sacada cria coleções com um mix de produtos cuidadosamente desenvolvidos com as melhores matérias-primas do mercado, na medida para a mulher exigente, feminina e original.'}},
      salinas: {initial: '/95966381/D_Catalogo_Top_Marcas_SALINAS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-181', meta: {title: 'SALINAS', tags: '', description: 'A praia carioca é a grande fonte inspiradora dos biquínis da Salinas. A marca, que surgiu em 1982 nas areias de Ipanema, se consagrou fazendo um beachwear confortável, com pitadas de humor e linguagem própria. Destaque no badalado catálogo da Victoria´s Secret, a Salinas já estampou capas e editoriais de revistas como Sports Illustrated e Vogue, e faz sucesso entre celebridades internacionais como a cantora Madonna e a top Naomi Campbell.'}},
      salsa: {initial: '/95966381/D_Catalogo_Top_Marcas_SALSA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-182', meta: {title: 'SALSA', tags: '', description: 'Marca tradicional de beachwear, a Salsa está há 21 anos no mercado traduzindo todo o know how da moda praia brasileira em peças que são sucesso aqui e lá fora.'}},
      schutz: {initial: '/95966381/D_Catalogo_Top_Marcas_SCHUTZ', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-183', meta: {title: 'SCHUTZ', tags: '', description: 'Comandada por Alexandre Birman, a Schutz faz parte do grupo Arezzo, que entende de sapatos como ninguém. Criada em agosto de 1995, a marca investe pesado em pesquisas de tendências, desenvolvimento de material e tecnologia, para garantir peças incríveis sem abrir mão do conforto. O resultado são coleções antenadas, disputadas par a par por quem entende do assunto.'}},
      'sd-acessorios': {initial: '/95966381/D_Catalogo_Top_Marcas_SDACESSORIOS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-184', meta: {title: 'SD ACESSÓRIOS', tags: '', description: 'Foi desenvolvendo acessórios para si mesma que a designer Sheila Morais chamou a atenção com suas peças criativas e com vocação statement.'}},
      'sh-design': {initial: '/95966381/D_Catalogo_Top_Marcas_SHDESIGN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-185', meta: {title: 'SH DESIGN', tags: '', description: 'Os brincos e pulseiras da marca têm um DNA cool e despretensioso, ao mesmo tempo que agregam charme e informação de moda aos looks. As peças têm um mix de materiais como couro, metais e cristais, que deixam as peças com uma pegada contemporânea.'}},
      'shop-126': {initial: '/95966381/D_Catalogo_Top_Marcas_SHOP126', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-186', meta: {title: 'SHOP 126', tags: '', description: 'Com talento para traduzir a espontaneidade do lifestyle carioca, a SHOP 126 cria coleções com o frescor e a modernidade das meninas do Rio, na medida para a consumidora urbana e de espírito jovem.'}},
      shoulder: {initial: '/95966381/D_Catalogo_Top_Marcas_SHOULDER', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-187', meta: {title: 'SHOULDER', tags: '', description: 'A Shoulder cria coleções para a mulher contemporânea, que procura a versatilidade na moda sem abrir mão de seu lado mais feminino.'}},
      silken: {initial: '/95966381/D_Catalogo_Top_Marcas_SILKEN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-188', meta: {title: 'SILKEN', tags: '', description: 'A Silken, das irmãs Ana Maria e Patricia Piva, nasceu de um desejo mútuo de ver a camisa feminina, um clássico atemporal, modernizado e customizado de uma maneira única.'}},
      'sofia-para-vix': {initial: '/95966381/D_Catalogo_Top_Marcas_SOFIAPARAVIX', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-189', meta: {title: 'SOFIA PARA VIX', tags: '', description: 'A Sofia by Vix nasceu do mix da sensualidade brasileira com o chique europeu e um senso estilo californiano ousado e confiante. A marca faz um beachwear sexy para jovens com uma visão única de moda.'}},
      speedo: {initial: '/95966381/D_Catalogo_Top_Marcas_SPEEDO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-190', meta: {title: 'SPEEDO', tags: '', description: 'Marca consagrada de sportswear, a Speedo está há mais de 30 anos fazendo história no mercado nacional, com uma linha completa de produtos up to date com as principais tendências do segmento esportivo. Destaque para a tecnologia de ponta, que faz das peças excelentes aliadas na performance esportiva.'}},
      spektre: {initial: '/95966381/D_Catalogo_Top_Marcas_SPEKTRE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-191', meta: {title: 'SPEKTRE', tags: '', description: 'A Spektre, marca de óculos de sol original de Milão, caiu no gosto de personas da moda com seus modelos de lentes espelhadas em uma combinação perfeita de elegância e estilo.'}},
      spezzato: {initial: '/95966381/D_Catalogo_Top_Marcas_SPEZZATO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-192', meta: {title: 'SPEZZATO', tags: '', description: 'Da parceria entre as sóciais Andréa Chammas Kurbhi e Roberta Nahas nasceu a Spezzato, marca paulistana com espírito inovador que rapidamente conquistou o mercado nacional. Obrigatória no closet da mulher que gosta de uma moda descomplicada, a marca não deixa de fora de suas coleções as melhores tendências de cada temporada.'}},
      stoux: {initial: '/95966381/D_Catalogo_Top_Marcas_STOUX', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-193', meta: {title: 'STOUX', tags: '', description: 'Sempre acompanhando as principais tendências, a Stoux desenvolve acessórios modernos para um público que ama estar em dia com a moda.'}},
      sub: {initial: '/95966381/D_Catalogo_Top_Marcas_SUB', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-194', meta: {title: 'SUB', tags: '', description: 'Veterana no mercado de beachwear, a SUB (Selection Of Unbelievable Beachwear) agora assina sua linha própria de moda praia, sob medida para mulheres de gosto apurado, que não abrem mão de peças exclusivas.'}},
      superga: {initial: '/95966381/D_Catalogo_Top_Marcas_SUPERGA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-195', meta: {title: 'SUPERGA', tags: '', description: 'Tradicional marca italiana, a Superga é famosa por seus tênis de sola vulcanizada, em uma cartela de cores cheia de bossa, perfeitos para quem não abre mão dos clássicos.'}},
      'super-suite-seventy-seven': {initial: '/95966381/D_Catalogo_Top_Marcas_SUPERSUITESEVNTYSEVEN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-196', meta: {title: 'SUPER SUITE SEVENTY SEVEN', tags: '', description: 'A Super Suite Seventy Seven, do paulistano Rodrigo Trussardi, nasceu em Nova York e ganhou o mundo. Com um estilo cool e atemporal, investe em peças de alfaiataria e outros clássicos do guarda-roupa feminino, mas sempre com um twist. É a marca queridinha das mulheres antenadas, que gostam de estar bem vestidas, independente dos modismos.'}},

      swarovski: {initial: '/95966381/D_Catalogo_Top_Marcas_SWAROVSKI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-197', meta: {title: 'SWAROVSKI', tags: '', description: 'Unindo design, criatividade e cristais que são referência em qualidade, a grife austríaca desenvolve acessórios que provocam desejo imadiato. Para as mais clássicas ou mais ousadas, a marca tem uma opção cheia de personalidade.'}},

      'talie-nk': {initial: '/95966381/D_Catalogo_Top_Marcas_TALIENK', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-198', meta: {title: 'TALIE NK', tags: '', description: 'A TalieNK, marca própria de Natalie Klein, traduz para sua identidade as melhores tendências de moda, sempre com um toque cosmopolita.'}},
      tanden: {initial: '/95966381/D_Catalogo_Top_Marcas_TANDEN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-199', meta: {title: 'TANDEN', tags: '', description: 'Entre linhas retas e orgânicas, a precisão é o traço principal da Tanden. A marca atualiza o conceito de roupa de festa com silhuetas esguias, técnicas da alfaiataria e um mix de produtos que vai muito além dos vestidos. A seda é a principal matéria-prima das criações da marca que reflete a elegância natural de suas consumidoras.'}},
      tantan: {initial: '/95966381/D_Catalogo_Top_Marcas_TANTAN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-200', meta: {title: 'TANTAN', tags: '', description: 'Marca paulistana com mais de 20 anos de história, a TanTan agrada em cheio a mulheres independentes e com informação de moda. No mix de produtos, tendências atuais e os básicos que agradam a mulher contemporânea ajudam a compor coleções sempre atuais.'}},
      tavi: {initial: '/95966381/D_Catalogo_Top_Marcas_TAVI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-201', meta: {title: 'TAVI', tags: '', description: 'Em dia com as principais tendências de moda, a grife chega ao mercado com sapatos de altíssima qualidade. Vendidas exclusivamente no OQVestir, as peças da Tavi são puro desejo. Escolha pelo menos um par para chamar de seu!'}},
      'tee-match': {initial: '/95966381/D_Catalogo_Top_Marcas_TEEMATCH', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-202', meta: {title: 'TEE MATCH', tags: '', description: 'A Tee Match, de Nicole Abramoff, mistura moda e arte com ilustrações exclusivas, excelência em suas matérias-primas e peças numeradas, traduzindo o lifestyle de mulheres modernas, antenadas e naturalmente femininas.'}},
      'tea-shirt': {initial: '/95966381/D_Catalogo_Top_Marcas_TEASHIRT', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-203', meta: {title: 'TEA SHIRT', tags: '', description: 'Comandada por uma estilista e uma designer gráfica, a marca desenvolve peças que unem moda e design. Feita para uma mulher contemporânea e prática, as camisetas têm tons neutros e recortes estratégicos e modernos.'}},
      thelure: {initial: '/95966381/D_Catalogo_Top_Marcas_THELURE', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-204', meta: {title: 'THELURE', tags: '', description: 'Em apenas quatro anos, as amigas Luciana Faria Nascimento e Stella Jacintho criaram uma das marcas mais hypadas do país. O sucesso da Thelure está nas coleções extensas, recheadas de peças ultra desejáveis, como a alfaiataria de acabamento perfeito e as estampas exclusivas, apresentadas de forma chique, sensual e despretensiosa.'}},
      tidsy: {initial: '/95966381/D_Catalogo_Top_Marcas_TIDSY', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-205', meta: {title: 'TIDSY', tags: '', description: 'Sempre focada na excelência da moda nacional, a Tidsy conquistou seu espaço criando peças em alfaiataria e uma linha de camisaria para a mulher contemporânea urbana, com coleções marcadas por um estilo despojado e, ao mesmo tempo, refinado.'}},

      tigga: {initial: '/95966381/D_Catalogo_Top_Marcas_TIGGA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-206', meta: {title: 'TIGGA', tags: '', description: 'A marca desenvolve brincos, pulseiras, colares e outros acessórios superfemininos que estão conquistando o público o charme e sofisticação de suas peças. A oficinada grife tem um ambiente superdescolado e leve, o que ajuda na criação de cada item, sempre cheio de detalhes únicos.'}},
      'tommy-hilfinger': {initial: '/95966381/D_Catalogo_Top_Marcas_TOMMYHILFINGER', sizes: [768, 1024], gpt: 'div-gpt-ad-1443193869828-0', meta: {title: 'TOMMY HILFINGER', tags: '', description: 'A grife é expert em retratar o lifestyle americano, com prints clássicas e alfaiataria certeira em versões reloaded. As camisetas polo são verdadeiros clássicos do guarda-roupa, ideais para looks de pegada boyish.'}},
      tishida: {initial: '/95966381/D_Catalogo_Top_Marcas_TISHIDA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-207', meta: {title: 'TISHIDA', tags: '', description: 'Com proposta contemporânea, a marca se prepõe a trabalhar um ready to wear prático e sem monotonia. Ou seja, peças com cortes atuais, limpos e bem elaborados, feitas em tecidos escolhidos com o critério do melhor toque, qualidade e caimento. No comando da grife está Tica Ishida, que tem passagem por muitas marcas de moda nacional.'}},

      totem: {initial: '/95966381/D_Catalogo_Top_Marcas_TOTEM', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-208', meta: {title: 'TOTEM', tags: '', description: 'A Totem sintetiza o lifestyle carioca em uma moda descontraída, sempre animada por estampas exclusivas e cores intensas.'}},
      'tree-acessorios': {initial: '/95966381/D_Catalogo_Top_Marcas_TREEACESSÓRIOS', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-209', meta: {title: 'TREE ACESSÓRIOS', tags: '', description: 'A Tree Acessórios nasceu de uma união entre as duas amigas Elisa Jardim e Graziela Hering. Tendo como base os conceitos da joalheria, a inspiração para desenvolvimento das peças vem da paixão por inovar e também da constante busca por atender aos desejos de suas clientes, mulheres modernas que entendem o poder dos acessórios.'}},
      triya: {initial: '/95966381/D_Catalogo_Top_Marcas_TRIYA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-210', meta: {title: 'TRIYA', tags: '', description: 'Com estilo leve e colorido, a Triya possui uma moda beachwear e uma linha completa de vestuário feminino em sintonia com as últimas tendências, ao mesmo tempo que se preocupa em desenvolver coleções fáceis de usar. Não à toa, a marca tornou-se referência de moda praia deluxe e tem sido habitué da seleção das meninas mais antenadas.'}},
      troa: {initial: '/95966381/D_Catalogo_Top_Marcas_TROÁ', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-211', meta: {title: 'TROÁ', tags: '', description: 'A Troá, de Camila Pires e Tatiana Amato, é expert em criar para a mulher moderna que não dispensa peças versáteis e, ao mesmo tempo, cheias de bossa. Com a proposta de reeditar a alta-costura da alfaiataria feminina, a Troá desenvolve peças exclusivas com caimento perfeito e acabamento impecável.'}},
      trousseau: {initial: '/95966381/D_Catalogo_Top_Marcas_TROUSSEAU', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-212', meta: {title: 'TROUSSEAU', tags: '', description: 'Pioneira no segmento de moda casa no Brasil, a Trousseau é reconhecida pelos produtos que valorizam os materiais nobres e a riqueza de detalhes.'}},
      valen: {initial: '/95966381/D_Catalogo_Top_Marcas_VALEN', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-213', meta: {title: 'VALEN', tags: '', description: 'Com essência hi low e elegância tipicamente carioca, o estilo da Valen passeia entre o urbano e o romântico. Seda e modelagens clássicas são apostas constantes da marca, mas também não faltam estampas exclusivas e básicos com detalhes únicos a cada coleção.'}},
      'vi-and-co': {initial: '/95966381/D_Catalogo_Top_Marcas_VIANDCO', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-214', meta: {title: 'VI AND CO', tags: '', description: 'Com a proposta de ser uma marca leve e despretensiosa, a Vi and Co tem conquistado cada vez mais espaço. Viviana e Corina Ximenes e Ana Laura Matos uniram forças na criação de moda para mulheres femininas, independentes e cosmopolitas.'}},
      vicenza: {initial: '/95966381/D_Catalogo_Top_Marcas_VICENZA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-215', meta: {title: 'VICENZA', tags: '', description: 'Marca inovadora de sapatos com essência brasileira e padrão internacional, a Vicenza aposta na equação design e estilo para assinar criações que agradam a mulheres contemporâneas e arrojadas.'}},

      'vinci': {initial: '/95966381/D_Catalogo_Top_Marcas_VINCISHOES', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-216', meta: {title: 'VINCISHOES', tags: '', description: 'Com foco no conforto, a especialidade da marca são as sapatilhas. Além de materiais premium, a grife investe em designs que se renovam a cada temporada, como pede o acelerado ritmo do mundo da moda. Para quem gosta de manter os pés no chão sem perder o charme!'}},

      'virzi-de-luca': {initial: '/95966381/D_Catalogo_Top_Marcas_VIRZIDELUCA', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-217', meta: {title: 'VIRZI+ DE LUCA', tags: '', description: 'A Virzi e De Luca nasceu de um encontro improvável, musas de duas gerações como descreveu a Vogue, Marcella Virzi e Betina De Luca são a representação do chique carioca. Conhecidas pelo bom gosto impecável,  a dupla se uniu para criar modelos de acessórios que revitalizassem o armário de qualquer mulher. Peças únicas em estilo e design, os modelos da marca são uma aliança entre a máxima sofisticação e nenhuma pretensão.'}},
      vix: {initial: '/95966381/D_Catalogo_Top_Marcas_VIX', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-218', meta: {title: 'VIX', tags: '', description: 'Em 2003, a estilista Paula Hermanny lançou nos Estados Unidos a marca Vix, batizada em homenagem à sua cidade natal, Vitória. A identidade brasileira fez sucesso entre as celebridades, que se apaixonaram pela modelagem perfeita e detalhes preciosos, como ferragens banhadas a ouro, acabamentos em couro e pedra jade. Estampas geométricas e animal prints estão entre os hits da Vix. Em 2007, a grife chegou ao Brasil já consagrada e passou a figurar no topo das wish-lists de moda praia.'}},
      'we-fit': {initial: '/95966381/D_Catalogo_Top_Marcas_WEFIT', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-219', meta: {title: 'WE FIT', tags: '', description: 'A We Fit, marca de moda fitness, une os benefícios dos tecidos tecnológicos com tendências para quem quer estar sempre na moda. As peças têm cores up to date e estampas que animam qualquer momento de bem estar e saúde.'}},
      'we-wood': {initial: '/95966381/D_Catalogo_Top_Marcas_WEWOOD', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-220', meta: {title: 'WE WOOD', tags: '', description: 'A WeWood nasceu em Florença, na Itália, combinando sustentabilidade e inovação. Desde 2010 a marca que assina relógios exclusivos em madeira, fabricados quase artesanalmente, com sobras do materiais que seriam descartadas. Cada relógio é único, já que a marca utiliza apenas materiais naturais em suas coleções.'}},
      yogini: {initial: '/95966381/D_Catalogo_Top_Marcas_YOGINI', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-221', meta: {title: 'YOGINI', tags: '', description: 'Com leveza e equilíbrio, a Yogini cria roupas e acessórios para a prática de yoga, e uma linha casual com estilo inconfundível, pensada para a mulher que está confortável dentro de si mesma, e, que já entendeu que charme vai além da aparência.'}},
      zerezes: {initial: '/95966381/D_Catalogo_Top_Marcas_ZEREZES', sizes: [768, 1024], gpt: 'div-gpt-ad-1441815559158-222', meta: {title: 'ZEREZES', tags: '', description: 'A marca de DNA carioca é expert na experimentação com novos materiais para o desenvolvimento de sua linha de óculos de sol. Um exemplo são os modelos feitos de madeira reciclada, extremamente leves. Para completar a alta qualidade do produto, todas as lentes têm proteção contra raios UVA/UVB.'}}

    }
  }
});
